feat!: give an error message when a service is disabled without setting an (external) hostname
accelleran/helm-charts pull request #142
Opened 2024-03-06 13:12 UTC by Wielewout

The combination of the 2 commits makes this a non breaking change for our own charts, but as there are now checks that would fail the code generation in some cases we still indicate it as breaking.

2024-03-19 10:05 UTC, ben-foxmoore commented
@Wielewout (@colinmhoward) Just FYI - I haven't forgotten about reviewing this 😅

The code change itself is relatively trivial, but something about the overall approach just doesn't sit right. I think essentially it feels a bit too much like hidden magic, which depends on the consuming chart to be structured in a specific way (using the same Kafka/NATS/Redis charts that we're using currently).

I haven't managed to think through this fully still, but I'm trying to work out if there's any alternative options for us to consider.

2024-05-31 15:14 UTC, Wielewout commented on charts/common/templates/_bootstrap.tpl
> +  "https://github.com/accelleran/helm-charts/tree/main/charts/common#bootstrap-hostnames"
This URL will only point to the correct section once this PR is merged. Currently it's already valid though as the readme file exists.

2024-06-03 09:15 UTC, dimgogos requested changes

2024-06-03 09:15 UTC, dimgogos commented on charts/common/README.md
> +Their are two ways to handle this:
```suggestion
There are two ways to handle this:
```

2024-06-03 09:15 UTC, dimgogos commented on charts/common/README.md
> +> It might occur that this failures happens in a nested part of the values file.
```suggestion
> It might occur that this failure happens in a nested part of the values file.
```

2024-06-03 10:02 UTC, dimgogos approved these changes

2024-06-03 10:07 UTC, merged